sudo: required
services:
  - docker

before_install:
  - docker build -t sassyg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sassyg/docker-react npm run test 

language: generic